#!/usr/bin/env bash

source "${CS_ROOT}/${CS_NAME}/lib/bucket"

case "$1" in
    add)
        shift
        bucket_add "$@"
        exit
        ;;
    remove)

        shift
        bucket_remove "$@"
        exit
        ;;
    list)
        shift
        bucket_list "$@"
        exit
        ;;
    *)
        printf -- 'error: %s: unknown command\n' "$1"
        exit
        ;;
esac
