#!/usr/bin/env bash
#::usage
#bpt init
#::summary
#Initialize files and directories
#::help
#Programs need a root path to be installed and their binary files
#must be available in PATH for the current user to use them. This
#command prepares all the files and directories necessary to
#ensure the proper functioning of bpt and the programs it installs.
#::pleh
source "${CS_ROOT}/${CS_NAME}/lib/init"

function init_all() {

    init_filesystem_directories
    init_program_directories
    init_preppend_path
    init_program_binary_to_path
    init_exec_perm_to_libexec
    init_clone_main_bucket

}
