#!/usr/bin/env bash

source "${CS_ROOT}/${CS_NAME}/lib/install"

function install_program() {

    local raw_input="$1"

    local sanitized_input=( $(get_bucket_and_program "$raw_input") )

    if [[ $? -eq 3 ]] ; then
        printf -- 'error: nested buckets not allowed\n'
        exit
    fi

    local bucket="${sanitized_input[0]}"
    local program="${sanitized_input[1]}"

    arrayPkgFiles=()
    check_pkg_dir_not_empty "$bucket"

    if [[ $? -ne 0 ]] ; then
        printf -- 'No packages available\n'
        exit
    fi

    arrayTargetPkg=()
    get_pkg_matches "$program"

    if [[ $? -eq 1 ]] ; then
        printf -- 'Package not found for %s\n' "$program"
        exit

    elif [[ "${#arrayTargetPkg[@]}" -eq 1 ]] ; then
        match_single "$bucket"

    elif [[ "${#arrayTargetPkg[@]}" -gt 1 ]] ; then
        match_multiple "$bucket"
    fi

}

if [[ ${#@} -eq 0 ]] ; then
    printf -- 'error: program name not given\n'
    exit
fi

install_program "$1"
