#!/usr/bin/env bash

source "${CS_ROOT}/${CS_NAME}/lib/install"

target_package="$1"

arrayPkgFiles=()
check_pkg_dir_not_empty

arrayTargetPkg=()
get_pkg_matches_with_target

if [[ "${#arrayTargetPkg[@]}" -eq 0 ]] ; then
    match_none

elif [[ "${#arrayTargetPkg[@]}" -eq 1 ]] ; then
    match_single
    unpack_tarball "${arrayTargetPkg[0]}"

elif [[ "${#arrayTargetPkg[@]}" -gt 1 ]] ; then
    match_multiple
fi
