#!/usr/bin/env bash
#::usage
#bpt install <bucket>/<program>
#::summary
#Install a saved package
#::help
#It reads the directory of packages and tries to install files that match
#the given name and the given bucket. If more than one package is available
#the user will be prompted to choose one.
#
#Downgrades and upgrades replace the current installation and don't save
#configuration files saved inside the program directory.
#::pleh
source "${CS_ROOT}/${CS_NAME}/lib/install"

function install_program() {

    local raw_input="$1"

    local sanitized_input=( $(get_bucket_and_program "$raw_input") )

    if [[ $? -eq 3 ]] ; then
        printf -- 'error: nested buckets not allowed\n'
        exit
    fi

    local bucket="${sanitized_input[0]}"
    local program="${sanitized_input[1]}"

    arrayPkgFiles=()
    check_pkg_dir_not_empty "$bucket"

    if [[ $? -ne 0 ]] ; then
        printf -- 'No packages available\n'
        exit
    fi

    arrayTargetPkg=()
    get_pkg_matches "$program"

    if [[ $? -eq 1 ]] ; then
        printf -- 'Package not found for %s\n' "$program"
        exit

    elif [[ "${#arrayTargetPkg[@]}" -eq 1 ]] ; then
        match_single "$bucket"

    elif [[ "${#arrayTargetPkg[@]}" -gt 1 ]] ; then
        match_multiple "$bucket"
    fi

}

if [[ ${#@} -eq 0 ]] ; then
    printf -- 'error: program name not given\n'
    exit
fi

install_program "$1"
